## Numpy array and basics

In [ ]:
import numpy as np


: 

## creating array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3] , [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list = [1,2,3]
print("Python list multiplication" , py_list * 2)

np_array = np.array([1,2,3])
print("Python array multiplication" , np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time:  0.04878997802734375

 Numpy operation time:  0.0048868656158447266


### creating array from scratch

In [4]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones ((4,4))
print("ones array: \n", ones)

full = np.full((3,3), 7)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0,10, 2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
random array: 
 [[0.13828463 0.23698081 0.95318988]
 [0.60143905 0.79916152 0.66809963]]
sequence array: 
 [0 2 4 6 8]


### vector , Matrix and Tensor

In [5]:
vector = np.array ([1,2,3,4,])
print("Vector: ", vector)

matrix = np.array ([[1, 2, 3],
                     [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]], 
                    [[5,6], [7,8]]])
print("Tensor: ", tensor)


Vector:  [1 2 3 4]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [6]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("Array: ", arr)
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size) 
print("Dtype ", arr.dtype)

Array:  [[1 2 3]
 [4 5 6]]
Shape  (2, 3)
Dimension  2
Size  6
Dtype  int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original Array", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped Array ", reshaped)

flattened = reshaped.flatten
print('\n Flattened array :', flattened)

#ravel (returns view, instead of copy)
raveled = reshaped. ravel()
print('\n Raveled array :', raveled )

#transpose
transposed = reshaped.T
print('\n Transposed array :', transposed)


Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array : <built-in method flatten of numpy.ndarray object at 0x1086abc90>

 Raveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
