## Numpy Array Operations ##

In [2]:
import numpy as np


In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("Basic Slicing returns: ", arr[3:9])
print("with step: ", arr[1:8:2])
print("Negative indexing: ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
Basic Slicing returns:  [4 5 6 7 8 9]
with step:  [2 4 6 8]
Negative indexing:  8


In [6]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("specific element", arr_2d[1,2]) # (1,2,3) is 0th row, (4,5,6) is 1st row and the last one is 2nd row. so 1st row, 2nd element ie. 6 
print("Entire Row",arr_2d[1])
print("Entire column", arr_2d[:, 1])


specific element 6
Entire Row [4 5 6]
Entire column [2 5 8]


## Sorting ##

In [6]:
unsorted = np.array([4,8,2,7,5,1,9,3,6])
print("Sorted array : ", np.sort(unsorted))

array_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2d array by column \n", np.sort(array_2d_unsorted, axis = 0))

Sorted array :  [1 2 3 4 5 6 7 8 9]
Sorted 2d array by column 
 [[1 1]
 [2 2]
 [3 3]]


## Filter ##

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number) 

Even numbers:  [ 2  4  6  8 10]


## Filter with Mask ##

In [9]:
mask = numbers > 5
print("Numbers greater than 5 : \n ", numbers[mask])

Numbers greater than 5 : 
  [ 6  7  8  9 10]


## fancy indexing v/s np.where()


In [10]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [11]:
condition_array = np.where(numbers > 5, numbers*3, numbers)
print(condition_array)

[ 1  2  3  4  5 18 21 24 27 30]


### Adding and removing Data

In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# combined = arr1 + arr2 
# print(combined)         # this is plain addition, but we need to combine the two arrays, so we use concatenate function/operation of numpy
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatibility shapes", a.shape == b.shape)

compatibility shapes True


In [37]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)


new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]
